### ISSUE TITLE
pkg 打包egg求助

### ISSUE THREAD

**Issue by meguoe** [MrSmallLiu/pkg-egg-example#1]
大神你好，我egg中使用了ali-mysql-client来访问数据库，使用pkg打包后运行发现无法正常连接到数据库，看到您改了一版egg-sequelize来适应pkg打包，不知能否看下ali-mysql-client该如何配置或修改才能适应pkg打包，请大神不吝赐教【抱拳】

**Comment by meguoe** [comment]
已解决！

**Comment by MrSmallLiu** [comment]
不好意思，刚看到您的邮件，打包时不需要使用我修改后的egg-sequelize，使用官网的即可。至于您的问题看到您说已经解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"meguoe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 中午1:15
收件人:&nbsp;"MrSmallLiu/pkg-egg-example"<pkg-egg-example@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[MrSmallLiu/pkg-egg-example] pkg 打包egg求助 (#1)





 
大神你好，我egg中使用了ali-mysql-client来访问数据库，使用pkg打包后运行发现无法正常连接到数据库，看到您改了一版egg-sequelize来适应pkg打包，不知能否看下ali-mysql-client该如何配置或修改才能适应pkg打包，请大神不吝赐教【抱拳】

**Comment by geesmart** [comment]
请问下在macos平台下面报这个错误，请问是什么问题呢？

./pkg-egg-example start /snapshot/pkg-egg-example --port=7007 --title=pkg-egg-example    
/snapshot/src/build.js
⚠️  AssertionError: /snapshot/pkg-egg-example/package.json should exist
⚠️  Command Error, enable `DEBUG=common-bin` for detail
