### ISSUE TITLE
AssertionError: /snapshot/pkg-egg-example/package.json should exist

### ISSUE THREAD

**Issue by geesmart** [MrSmallLiu/pkg-egg-example#2]
请问下在macos平台下面报这个错误，请问是什么问题呢？

./pkg-egg-example start /snapshot/pkg-egg-example --port=7007 --title=pkg-egg-example
/snapshot/src/build.js
⚠️ AssertionError: /snapshot/pkg-egg-example/package.json should exist
⚠️ Command Error, enable DEBUG=common-bin for detail

**Comment by yyshengfan** [comment]
遇到了同样的问题！

**Comment by MrSmallLiu** [comment]
在我的示例中添加了打印路径的代码，它会输出路径。 这个路径在pkg中会是一个虚拟路径，在运行的时候指定该路径即可。不需要源码。 文档参考：https://blog.csdn.net/qq_35241223/article/details/97306900?spm=1001.2014.3001.5501

**Comment by yyshengfan** [comment]
是的我们按照你的命令在运行的时候指定了，但是他运行会去这个虚拟路径下找package.json，这个不太懂！需要怎么修改一下吗？
src % ./pkg-egg-example start /snapshot/pkg-egg-example --port=7007 --title=pkg-egg-example
/snapshot/src/build.js
⚠️  AssertionError: /snapshot/pkg-egg-example/package.json should exist
⚠️  Command Error, enable `DEBUG=common-bin` for detail

**Comment by MrSmallLiu** [comment]
先直接执行可执行文件，会在最上面输出路径。这个路径就是虚拟路径

**Comment by yyshengfan** [comment]
/snapshot/src/build.js
这个是我打印出来的，意思/snapshot/src这个就是我的虚拟路径我需要指定为它是吧！
我试了还是不行，或者我不指定可以吗？
我试了会报：
Error: Cannot find module '/Users/sh07047ml/hui/pkg-egg-example/src/--no-deprecation'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1776:46)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by MrSmallLiu** [comment]
不指定不可以。 这个是egg-scripts中需要的。  --no-deprecation是egg在2.14增加的。不影响功能。 将egg版本回退一些即可

**Comment by yyshengfan** [comment]
好的谢谢我试试看

**Comment by yyshengfan** [comment]
试了一下降低了版本还是不行，在midway下边也会报这个错如果是版本的问题我不打包运行也会有问题吧，很是焦灼。。。

**Comment by MrSmallLiu** [comment]
那个版本问题影响的是打包后运行，不是影响直接运行的。那个参数不是个bug

**Comment by yyshengfan** [comment]
嗯呢，我找了一下这个报错也没看到相关的资料，我现在版本降到2.11.2了，打包运行还是回报这个错，大佬能帮忙解决一下吗？或者我去linux环境下试试看

**Comment by yyshengfan** [comment]
linux我试了下也不行😂😂。。。。。。
